### PR TITLE
update nokogiri to 1.8.1

### PR DESCRIPTION
**Pull request by alexcopquin**
addresses nokogiri [issue 1673](https://github.com/sparklemotion/nokogiri/issues/1673)

### CODE REVIEW

**Review by florrain — CHANGES_REQUESTED** [review]
Hey @alexcopquin - Thanks for your contribution!

Two requests:
- Can you put the version bump into its own commit?
- Relax the versioning to any 1.8 patches `"< 1.9"`

Thanks!

**Comment by alexcopquin** [comment]
@florrain changes done, pls review

**Comment by alexcopquin** [comment]
👍

**Comment by florrain** [comment]
@alexcopquin - Version 0.3.2 is published on [rubygems.org](https://rubygems.org/gems/responsys-api/versions/0.3.2)

**Pull request merged**
